name: clean_bspline_policy_haoyu_left

shape_meta: &shape_meta
  obs:
    head_image:
      shape: [3, 128, 128]
      type: rgb
    left_wrist_image:
      shape: [3, 128, 128]
      type: rgb
    arm_pos_l:
      shape: [3]
    arm_quat_l:
      shape: [4]
    gripper_pos_l:
      shape: [1]

  action:
    shape: [10]

dataset_path: &dataset_path data/clean_bspline_policy_haoyu_left.hdf5
abs_action: &abs_action True

env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
  shape_meta: *shape_meta
  dataset_path: *dataset_path
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  abs_action: *abs_action
  rotation_rep: 'rotation_6d'
  use_legacy_normalizer: False
  use_cache: True
  cache_suffix: clean_bspline_policy_haoyu_left_action10_rot6d
  cache_decoded_replay: False
  cache_preprocessed_samples: False
  cache_preprocessed_device: cpu
  cache_preprocessed_share_memory: False
  cache_preprocessed_rgb_dtype: float32
  seed: 42
  val_ratio: 0.0
